[tool.poetry]
name = "zh-crawler"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "3.10.8"
psycopg2-binary = "2.9.5"
requests = "2.28.1"
beautifulsoup4 = "4.11.1"

[tool.poetry.group.alembic.dependencies]
alembic = "^1.8.0"
